<a href="https://colab.research.google.com/github/JacquelineGiPe/Bootcamp-DS-Proyecto-DS/blob/main/Actividad_7_Limpieza_datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Introducción

Mi nombre es **Jacqueline Giraldo** y en esta Actividad VII - Data Wrangling (Limpieza de Datos), abordaré la limpieza de un conjunto de datos sobre las tasas de suicidio.

### Consigna

1. **Limpieza de Problemas**:
   - **Outliers**: Tratamiento de valores atípicos para asegurar que no distorsionen los resultados del análisis.
   - **Duplicados**: Eliminación de registros duplicados que pueden influir negativamente en la integridad del análisis.
   - **Valores Nulos**: Manejo de valores faltantes mediante técnicas de imputación adecuadas.

2. **Imputación de Valores Nulos**:
   - Decidir si es posible utilizar técnicas de imputación sensible o múltiple para manejar los valores nulos en el conjunto de datos.

### Descripción del Conjunto de Datos

El conjunto de datos en cuestión contiene información detallada sobre las tasas de suicidio a nivel regional y nacional, incluyendo variables como:

- `RegionCode`, `RegionName`, `CountryCode`, `CountryName`: Información geográfica.
- `Year`: Año de la observación.
- `Sex`: Género de la población.
- `SuicideCount`: Número de suicidios registrados.
- `CauseSpecificDeathPercentage`, `StdDeathRate`, `DeathRatePer100K`, `Population`, `GDP`, `GDPPerCapita`, `GNI`, `GNIPerCapita`, `InflationRate`, `EmploymentPopulationRatio`: Variables cuantitativas relacionadas con la mortalidad y factores socioeconómicos.

El objetivo de esta actividad es realizar una limpieza de estos datos para garantizar su utilidad en posteriores análisis y estudios. Con un enfoque en el tratamiento de outliers, duplicados y valores nulos.

# **Limpieza de datos**

In [ ]:
import pandas as pd

df = pd.read_csv('suicide_rates.csv')

df.head()

,RegionCode,RegionName,CountryCode,CountryName,Year,Sex,SuicideCount,CauseSpecificDeathPercentage,StdDeathRate,DeathRatePer100K,Population,GDP,GDPPerCapita,GNI,GNIPerCapita,InflationRate,EmploymentPopulationRatio
0,EU,Europe,ALB,Albania,1992,Male,33,0.331959,2.335802,2.076386,3247039.0,6.521750e+08,200.852220,9.061842e+08,1740.0,226.005421,45.315
1,EU,Europe,ALB,Albania,1992,Female,14,0.191860,0.866420,0.874563,3247039.0,6.521750e+08,200.852220,9.061842e+08,1740.0,226.005421,45.315
2,EU,Europe,ALB,Albania,1993,Male,46,0.477724,3.330938,2.937233,3227287.0,1.185315e+09,367.279225,1.024263e+09,2110.0,85.004751,47.798
3,EU,Europe,ALB,Albania,1993,Female,27,0.385164,1.755077,1.686025,3227287.0,1.185315e+09,367.279225,1.024263e+09,2110.0,85.004751,47.798
4,EU,Europe,ALB,Albania,1994,Male,37,0.419406,2.678796,2.332619,3207536.0,1.880951e+09,586.416135,1.216681e+09,2300.0,22.565053,50.086

In [ ]:
df.shape

(5928, 17)

In [ ]:
df.describe()

,Year,SuicideCount,CauseSpecificDeathPercentage,StdDeathRate,DeathRatePer100K,Population,GDP,GDPPerCapita,GNI,GNIPerCapita,InflationRate,EmploymentPopulationRatio
count,5928.000000,5928.000000,5927.000000,5720.000000,5720.000000,5.632000e+03,5.566000e+03,5566.000000,5.430000e+03,5390.000000,5205.000000,5372.000000
mean,2005.740047,1267.660088,1.264219,9.649577,10.688010,2.456184e+07,4.883873e+11,17423.508254,4.975887e+11,22147.217069,20.286455,55.750811
std,8.745704,3887.349179,1.188728,10.715036,11.763056,4.531538e+07,1.653792e+12,19333.786133,1.688950e+12,18888.063046,163.114790,8.141714
min,1990.000000,0.000000,0.000000,0.000000,0.000000,4.054200e+04,2.197630e+08,60.235121,2.082832e+08,780.000000,-10.630097,32.026000
25%,1999.000000,30.000000,0.431064,2.554089,2.741542,2.613805e+06,1.163490e+10,3945.243570,1.176850e+10,8670.000000,1.498961,50.791000
50%,2006.000000,226.500000,0.882576,6.061477,6.813998,6.888434e+06,6.268216e+10,9708.141348,5.987715e+10,16150.000000,3.038888,56.021000
75%,2013.000000,836.000000,1.870304,13.064868,14.354849,2.533364e+07,3.010000e+11,25197.265600,3.055000e+11,29530.000000,6.536199,60.415250
max,2022.000000,51464.000000,16.666667,80.261488,83.522190,3.320316e+08,2.330000e+13,133711.794400,2.370000e+13,152630.000000,4734.914347,87.518000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5928 entries, 0 to 5927
Data columns (total 17 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   RegionCode                    5928 non-null   object
 1   RegionName                    5928 non-null   object
 2   CountryCode                   5928 non-null   object
 3   CountryName                   5928 non-null   object
 4   Year                          5928 non-null   int64
 5   Sex                           5928 non-null   object
 6   SuicideCount                  5928 non-null   int64
 7   CauseSpecificDeathPercentage  5927 non-null   float64
 8   StdDeathRate                  5720 non-null   float64
 9   DeathRatePer100K              5720 non-null   float64
 10  Population                    5632 non-null   float64
 11  GDP                           5566 non-null   float64
 12  GDPPerCapita                  5566 non-null   float64
 13  GNI                           5430 non-null   float64
 14  GNIPerCapita                  5390 non-null   float64
 15  InflationRate                 5205 non-null   float64
 16  EmploymentPopulationRatio     5372 non-null   float64
dtypes: float64(10), int64(2), object(5)
memory usage: 787.4+ KB

In [ ]:
pais = set(df['CountryName'].to_list())
year = set(df["Year"].to_list())
pais, year

({'Albania',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Bosnia and Herzegovina',
  'Brazil',
  'Brunei Darussalam',
  'Bulgaria',
  'Cabo Verde',
  'Canada',
  'Chile',
  'China, Hong Kong SAR',
  'Colombia',
  'Costa Rica',
  'Croatia',
  'Cuba',
  'Cyprus',
  'Czechia',
  'Denmark',
  'Dominica',
  'Dominican Republic',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Estonia',
  'Fiji',
  'Finland',
  'France',
  'French Guiana',
  'Georgia',
  'Germany',
  'Greece',
  'Grenada',
  'Guadeloupe',
  'Guatemala',
  'Guyana',
  'Hungary',
  'Iceland',
  'Iran (Islamic Republic of)',
  'Iraq',
  'Ireland',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kuwait',
  'Kyrgyzstan',
  'Latvia',
  'Lebanon',
  'Lithuania',
  'Luxembourg',
  'Malaysia',
  'Maldives',
  'Malta',
  'Martinique',
  'Mauritius',
  'Mayotte',
  'Mexico',
  'Mongolia',
  'Montenegro',
  'Netherlands',
  'New Zealand',
  'Nicaragua',
  'North Macedonia',
  'Norway',
  'Oman',
  'Panama',
  'Paraguay',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Puerto Rico',
  'Qatar',
  'R?union',
  'Republic of Korea',
  'Republic of Moldova',
  'Romania',
  'Russian Federation',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Vincent and the Grenadines',
  'Serbia',
  'Seychelles',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'South Africa',
  'Spain',
  'Sri Lanka',
  'Suriname',
  'Sweden',
  'Switzerland',
  'Syrian Arab Republic',
  'T?rkiye',
  'Tajikistan',
  'Thailand',
  'Trinidad and Tobago',
  'Turkmenistan',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom of Great Britain and Northern Ireland',
  'United States of America',
  'Uruguay',
  'Uzbekistan',
  'Venezuela (Bolivarian Republic of)'},
 {1990,
  1991,
  1992,
  1993,
  1994,
  1995,
  1996,
  1997,
  1998,
  1999,
  2000,
  2001,
  2002,
  2003,
  2004,
  2005,
  2006,
  2007,
  2008,
  2009,
  2010,
  2011,
  2012,
  2013,
  2014,
  2015,
  2016,
  2017,
  2018,
  2019,
  2020,
  2021,
  2022})

In [ ]:
#Tratamento de valores negativos
#generalizado y no (cada columna.)

df["Year"] = df["Year"].apply(lambda x: np.nan if x < 0 else x)

In [77]:
df.drop_duplicates(inplace=True)
df

<ipython-input-77-769a7c6c9b00>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop_duplicates(inplace=True)

,RegionCode,RegionName,CountryCode,CountryName,Year,Sex,SuicideCount,CauseSpecificDeathPercentage,StdDeathRate,DeathRatePer100K,Population,GDP,GDPPerCapita,GNI,GNIPerCapita,InflationRate,EmploymentPopulationRatio
0,EU,Europe,ALB,Albania,1992,Male,33.0,0.331959,2.335802,2.076386,3247039.0,6.521750e+08,200.852220,9.061842e+08,1740.0,226.005421,56.24086
1,EU,Europe,ALB,Albania,1992,Female,14.0,0.191860,0.866420,0.874563,3247039.0,6.521750e+08,200.852220,9.061842e+08,1740.0,226.005421,56.24086
2,EU,Europe,ALB,Albania,1993,Male,46.0,0.477724,3.330938,2.937233,3227287.0,1.185315e+09,367.279225,1.024263e+09,2110.0,85.004751,47.79800
3,EU,Europe,ALB,Albania,1993,Female,27.0,0.385164,1.755077,1.686025,3227287.0,1.185315e+09,367.279225,1.024263e+09,2110.0,85.004751,47.79800
4,EU,Europe,ALB,Albania,1994,Male,37.0,0.419406,2.678796,2.332619,3207536.0,1.880951e+09,586.416135,1.216681e+09,2300.0,22.565053,50.08600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5366,AF,Africa,ZAF,South Africa,2016,Female,78.0,0.035226,0.278158,0.273954,56422274.0,3.240000e+11,5735.066787,3.360000e+11,13350.0,6.571396,56.24086
5368,AF,Africa,ZAF,South Africa,2017,Male,281.0,0.115853,1.020338,0.999238,56641209.0,3.810000e+11,6734.475153,3.370000e+11,13560.0,5.184247,56.24086
5369,AF,Africa,ZAF,South Africa,2017,Female,95.0,0.043992,0.326797,0.328853,56641209.0,3.810000e+11,6734.475153,3.370000e+11,13560.0,5.184247,56.24086
5370,AF,Africa,ZAF,South Africa,2018,Male,232.0,0.097257,0.813995,0.814175,57339635.0,4.050000e+11,7067.724165,3.670000e+11,13930.0,4.517165,56.24086
5371,AF,Africa,ZAF,South Africa,2018,Female,82.0,0.038353,0.284316,0.279888,57339635.0,4.050000e+11,7067.724165,3.670000e+11,13930.0,4.517165,56.24086

In [ ]:
#imputar valores faltantes
for column in ["SuicideCount"]:
  median_value = df[column].median()
  df[column].fillna(median_value, inplace= True)

df["SuicideCount"]

0       33
1       14
2       46
3       27
4       37
        ..
5923     0
5924    68
5925    17
5926    79
5927    20
Name: SuicideCount, Length: 5928, dtype: int64

In [ ]:
pais

{'Albania',
 'Antigua and Barbuda',
 'Argentina',
 'Armenia',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Bahamas',
 'Bahrain',
 'Barbados',
 'Belarus',
 'Belgium',
 'Belize',
 'Bosnia and Herzegovina',
 'Brazil',
 'Brunei Darussalam',
 'Bulgaria',
 'Cabo Verde',
 'Canada',
 'Chile',
 'China, Hong Kong SAR',
 'Colombia',
 'Costa Rica',
 'Croatia',
 'Cuba',
 'Cyprus',
 'Czechia',
 'Denmark',
 'Dominica',
 'Dominican Republic',
 'Ecuador',
 'Egypt',
 'El Salvador',
 'Estonia',
 'Fiji',
 'Finland',
 'France',
 'French Guiana',
 'Georgia',
 'Germany',
 'Greece',
 'Grenada',
 'Guadeloupe',
 'Guatemala',
 'Guyana',
 'Hungary',
 'Iceland',
 'Iran (Islamic Republic of)',
 'Iraq',
 'Ireland',
 'Israel',
 'Italy',
 'Jamaica',
 'Japan',
 'Jordan',
 'Kazakhstan',
 'Kuwait',
 'Kyrgyzstan',
 'Latvia',
 'Lebanon',
 'Lithuania',
 'Luxembourg',
 'Malaysia',
 'Maldives',
 'Malta',
 'Martinique',
 'Mauritius',
 'Mayotte',
 'Mexico',
 'Mongolia',
 'Montenegro',
 'Netherlands',
 'New Zealand',
 'Nicaragua',
 'North Macedonia',
 'Norway',
 'Oman',
 'Panama',
 'Paraguay',
 'Peru',
 'Philippines',
 'Poland',
 'Portugal',
 'Puerto Rico',
 'Qatar',
 'R?union',
 'Republic of Korea',
 'Republic of Moldova',
 'Romania',
 'Russian Federation',
 'Saint Kitts and Nevis',
 'Saint Lucia',
 'Saint Vincent and the Grenadines',
 'Serbia',
 'Seychelles',
 'Singapore',
 'Slovakia',
 'Slovenia',
 'South Africa',
 'Spain',
 'Sri Lanka',
 'Suriname',
 'Sweden',
 'Switzerland',
 'Syrian Arab Republic',
 'T?rkiye',
 'Tajikistan',
 'Thailand',
 'Trinidad and Tobago',
 'Turkmenistan',
 'Ukraine',
 'United Arab Emirates',
 'United Kingdom of Great Britain and Northern Ireland',
 'United States of America',
 'Uruguay',
 'Uzbekistan',
 'Venezuela (Bolivarian Republic of)'}

In [82]:
# Mapeo de datos

mapeo_ciudad = {

    'R?union': 'Reunion',
    'T?rkiye' : 'Turkiye',
    'yoajajja' : 'Albania'
}

df["CountryName"].replace(mapeo_ciudad, inplace = True)

set( df["CountryName"].to_list())

{'Albania',
 'Armenia',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Bahamas',
 'Bahrain',
 'Barbados',
 'Belarus',
 'Belgium',
 'Belize',
 'Brazil',
 'Brunei Darussalam',
 'Bulgaria',
 'Cabo Verde',
 'Canada',
 'Chile',
 'China, Hong Kong SAR',
 'Colombia',
 'Costa Rica',
 'Croatia',
 'Cyprus',
 'Czechia',
 'Denmark',
 'Dominican Republic',
 'Ecuador',
 'Egypt',
 'El Salvador',
 'Estonia',
 'Fiji',
 'Finland',
 'France',
 'Georgia',
 'Germany',
 'Greece',
 'Guatemala',
 'Guyana',
 'Hungary',
 'Iceland',
 'Iran (Islamic Republic of)',
 'Iraq',
 'Ireland',
 'Israel',
 'Italy',
 'Jamaica',
 'Japan',
 'Jordan',
 'Kazakhstan',
 'Kuwait',
 'Kyrgyzstan',
 'Latvia',
 'Lebanon',
 'Lithuania',
 'Luxembourg',
 'Malaysia',
 'Maldives',
 'Malta',
 'Mauritius',
 'Mexico',
 'Mongolia',
 'Montenegro',
 'Netherlands',
 'New Zealand',
 'Nicaragua',
 'North Macedonia',
 'Norway',
 'Oman',
 'Panama',
 'Paraguay',
 'Peru',
 'Philippines',
 'Poland',
 'Portugal',
 'Qatar',
 'Republic of Korea',
 'Republic of Moldova',
 'Romania',
 'Russian Federation',
 'Saint Lucia',
 'Saint Vincent and the Grenadines',
 'Serbia',
 'Singapore',
 'Slovakia',
 'Slovenia',
 'South Africa',
 'Spain',
 'Sri Lanka',
 'Suriname',
 'Sweden',
 'Switzerland',
 'Tajikistan',
 'Thailand',
 'Trinidad and Tobago',
 'Turkiye',
 'Ukraine',
 'United Arab Emirates',
 'United Kingdom of Great Britain and Northern Ireland',
 'United States of America',
 'Uruguay',
 'Uzbekistan',
 'Venezuela (Bolivarian Republic of)'}

In [79]:
#Elimina los valones nulos del dataframe

df = df.dropna()
df

,RegionCode,RegionName,CountryCode,CountryName,Year,Sex,SuicideCount,CauseSpecificDeathPercentage,StdDeathRate,DeathRatePer100K,Population,GDP,GDPPerCapita,GNI,GNIPerCapita,InflationRate,EmploymentPopulationRatio
0,EU,Europe,ALB,Albania,1992,Male,33.0,0.331959,2.335802,2.076386,3247039.0,6.521750e+08,200.852220,9.061842e+08,1740.0,226.005421,56.24086
1,EU,Europe,ALB,Albania,1992,Female,14.0,0.191860,0.866420,0.874563,3247039.0,6.521750e+08,200.852220,9.061842e+08,1740.0,226.005421,56.24086
2,EU,Europe,ALB,Albania,1993,Male,46.0,0.477724,3.330938,2.937233,3227287.0,1.185315e+09,367.279225,1.024263e+09,2110.0,85.004751,47.79800
3,EU,Europe,ALB,Albania,1993,Female,27.0,0.385164,1.755077,1.686025,3227287.0,1.185315e+09,367.279225,1.024263e+09,2110.0,85.004751,47.79800
4,EU,Europe,ALB,Albania,1994,Male,37.0,0.419406,2.678796,2.332619,3207536.0,1.880951e+09,586.416135,1.216681e+09,2300.0,22.565053,50.08600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5366,AF,Africa,ZAF,South Africa,2016,Female,78.0,0.035226,0.278158,0.273954,56422274.0,3.240000e+11,5735.066787,3.360000e+11,13350.0,6.571396,56.24086
5368,AF,Africa,ZAF,South Africa,2017,Male,281.0,0.115853,1.020338,0.999238,56641209.0,3.810000e+11,6734.475153,3.370000e+11,13560.0,5.184247,56.24086
5369,AF,Africa,ZAF,South Africa,2017,Female,95.0,0.043992,0.326797,0.328853,56641209.0,3.810000e+11,6734.475153,3.370000e+11,13560.0,5.184247,56.24086
5370,AF,Africa,ZAF,South Africa,2018,Male,232.0,0.097257,0.813995,0.814175,57339635.0,4.050000e+11,7067.724165,3.670000e+11,13930.0,4.517165,56.24086
5371,AF,Africa,ZAF,South Africa,2018,Female,82.0,0.038353,0.284316,0.279888,57339635.0,4.050000e+11,7067.724165,3.670000e+11,13930.0,4.517165,56.24086

In [86]:
#muestra la cantidad de datos como not a number

df.isna().sum().sum()

0

# **Resolucion de problema de outliers con metodo Zscore**

In [94]:
import pandas as pd
import numpy as np
from scipy import stats

variables_outliers = df[["CauseSpecificDeathPercentage",
    "StdDeathRate",
    "DeathRatePer100K",
    "Population",
    "GDP",
    "GDPPerCapita",
    "GNI",
    "GNIPerCapita",
    "InflationRate",
    "EmploymentPopulationRatio"]]

for column in variables_outliers:
   z_scores = np.abs(stats.zscore(variables_outliers[column].dropna()))  # Calcular Z-scores, ignorar NaNs
   variables_outliers = variables_outliers[(z_scores < 3)]  # Filtrar valores con Z-score menor que 3

variables_outliers.describe()

,CauseSpecificDeathPercentage,StdDeathRate,DeathRatePer100K,Population,GDP,GDPPerCapita,GNI,GNIPerCapita,InflationRate,EmploymentPopulationRatio
count,4164.000000,4164.000000,4164.000000,4.164000e+03,4.164000e+03,4164.000000,4.164000e+03,4164.000000,4164.000000,4164.000000
mean,1.138939,7.857595,8.781038,1.319311e+07,1.877242e+11,15556.893132,1.832352e+11,19792.837408,5.338138,56.365274
std,0.857876,6.758637,7.594077,1.701595e+07,2.788778e+11,14711.356492,2.729801e+11,13338.593488,7.763165,4.569761
min,0.000000,0.000000,0.000000,1.043320e+05,3.160074e+08,157.063550,3.122460e+08,1080.000000,-8.525170,45.784000
25%,0.463014,2.548038,2.729758,2.622105e+06,1.317217e+10,4020.806245,1.253428e+10,8670.000000,1.490133,53.549000
50%,0.904382,5.946767,6.795331,6.091188e+06,6.023121e+10,10148.342400,5.604956e+10,16810.000000,3.010969,56.240860
75%,1.726089,10.804762,11.975325,1.671145e+07,2.530000e+11,22806.197380,2.460000e+11,27215.000000,6.353296,59.336000
max,3.518663,28.966381,32.243232,8.664845e+07,1.660000e+12,59407.698050,1.400000e+12,60760.000000,66.007034,66.736000